import type { SignalBrief } from "@/lib/types";

const now = "2026-05-18T09:52:00.000Z";

export const briefs: SignalBrief[] = [
  {
    id: "g7-ai-safety-data-rules",
    title: "G7 nations agree on AI safety framework and cross-border data rules",
    summary: "Leaders announced voluntary standards for responsible AI development and new principles for data flows that balance innovation with citizen protections.",
    keyPoints: [
      "Voluntary AI safety commitments across G7 members.",
      "New data transfer principles aim to reduce compliance friction.",
      "Implementation guidance is expected before Q4 2026."
    ],
    whyItMatters: "The framework could shape how AI products, cloud providers, and regulated businesses operate across major markets.",
    whoIsAffected: ["AI companies", "Cloud platforms", "Policy teams", "Privacy officers"],
    sourceName: "Global Affairs Desk",
    sourceUrl: "https://example.com/global-affairs",
    category: "Politics & Policy",
    subcategory: "AI Policy",
    region: "Global",
    publishedAt: now,
    imageUrl: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=1600&q=80",
    originalUrl: "https://example.com/g7-ai-safety-data-rules",
    readTime: "5 min",
    trustScore: 92,
    tags: ["AI policy", "G7", "Data transfers"],
    contentType: "policy_update",
    providerType: "api",
    sensitivityLevel: "legal",
    disclaimerRequired: true,
    fetchedAt: now
  },
  {
    id: "ceasefire-talks-cautious-optimism",
    title: "Ceasefire talks resume with cautious optimism",
    summary: "Regional negotiators reopened talks after a fragile pause, with humanitarian access and border monitoring still the most difficult points.",
    keyPoints: ["Talks restarted with international observers.", "Humanitarian corridors remain contested.", "Markets reacted cautiously to the renewed negotiations."],
    whyItMatters: "Conflict de-escalation could affect aid delivery, migration flows, fuel prices, and regional security planning.",
    whoIsAffected: ["Civilians", "Aid agencies", "Regional businesses"],
    sourceName: "IntelliNews",
    sourceUrl: "https://example.com/intellinews",
    category: "World",
    region: "Europe",
    publishedAt: "2026-05-18T07:50:00.000Z",
    imageUrl: "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?auto=format&fit=crop&w=900&q=80",
    originalUrl: "https://example.com/ceasefire-talks",
    readTime: "3 min",
    trustScore: 87,
    tags: ["Diplomacy", "Conflict", "Europe"],
    contentType: "article",
    providerType: "rss",
    fetchedAt: now
  },
  {
    id: "canada-work-permit-high-demand",
    title: "Canada updates work permit rules for high-demand occupations",
    summary: "Canada signalled adjustments to work permit processing for shortage roles, with priority pathways expected to benefit healthcare and technical applicants.",
    keyPoints: ["High-demand roles receive clearer processing priority.", "Applicants still need to verify official eligibility criteria.", "Employers may need updated documentation for supported applications."],
    whyItMatters: "Policy changes can affect application timing, employer hiring plans, and student-to-work transition decisions.",
    whoIsAffected: ["Skilled workers", "Canadian employers", "International students"],
    sourceName: "Borderline Brief",
    sourceUrl: "https://www.canada.ca/en/immigration-refugees-citizenship/news.html",
    category: "Visa & Immigration",
    subcategory: "Work permit",
    region: "North America",
    country: "Canada",
    publishedAt: "2026-05-18T06:45:00.000Z",
    imageUrl: "https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=900&q=80",
    originalUrl: "https://www.canada.ca/en/immigration-refugees-citizenship/news.html",
    readTime: "4 min",
    trustScore: 96,
    tags: ["Canada", "Work permit", "High-demand roles"],
    contentType: "visa_update",
    providerType: "official_update_page",
    sensitivityLevel: "immigration",
    disclaimerRequired: true,
    fetchedAt: now
  },
  {
    id: "london-councils-clean-air-grants",
    title: "London councils expand clean-air business grants",
    summary: "Local authorities are widening support for small businesses upgrading vehicles and equipment ahead of new air-quality enforcement windows.",
    keyPoints: ["Grant windows are expanding across several boroughs.", "Eligibility differs by local authority.", "Business owners should check council pages before applying."],
    whyItMatters: "Local policy shifts can affect operating costs, delivery fleets, and compliance timelines for small businesses.",
    whoIsAffected: ["Small businesses", "Drivers", "Local residents"],
    sourceName: "Local Signal UK",
    sourceUrl: "https://example.com/local-signal",
    category: "Local",
    subcategory: "Public sector",
    region: "UK",
    country: "UK",
    publishedAt: "2026-05-18T05:55:00.000Z",
    imageUrl: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=900&q=80",
    originalUrl: "https://example.com/london-clean-air-grants",
    readTime: "3 min",
    trustScore: 82,
    tags: ["Local", "London", "Business grants"],
    contentType: "policy_update",
    providerType: "rss",
    sensitivityLevel: "legal",
    disclaimerRequired: true,
    fetchedAt: now
  },
  {
    id: "nigeria-business-liquidity-signal",
    title: "Nigeria business brief: markets watch liquidity and currency signals",
    summary: "A local business feed highlights pressure around exchange rates, liquidity guidance, import costs, and investor sentiment.",
    keyPoints: ["Markets are watching liquidity and currency guidance.", "Business impact is strongest for importers and banks.", "Publisher attribution appears on each normalized story."],
    whyItMatters: "Country-level business coverage helps readers understand local impact before it appears in broad international headlines.",
    whoIsAffected: ["Investors", "Importers", "Banks", "Small businesses"],
    sourceName: "Business Desk",
    sourceUrl: "https://example.com/business-desk",
    category: "Startups & Business",
    subcategory: "Business/Finance",
    region: "Africa",
    country: "Nigeria",
    publishedAt: "2026-05-18T05:10:00.000Z",
    imageUrl: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?auto=format&fit=crop&w=900&q=80",
    originalUrl: "https://example.com/nigeria-business-liquidity-signal",
    readTime: "4 min",
    trustScore: 82,
    tags: ["Nigeria", "Business", "Markets", "Investment"],
    contentType: "article",
    providerType: "api",
    fetchedAt: now
  },
  {
    id: "nigeria-student-visa-community-pulse",
    title: "Community pulse: student visa timelines and proof-of-funds concerns trend locally",
    summary: "A community pulse signal shows rising public discussion around study routes, currency pressure, and documentation anxiety. Treat as public sentiment, not verified policy.",
    keyPoints: ["Community signals are not official guidance.", "Topic volume suggests student concern is rising.", "Official visa pages should be used for decisions."],
    whyItMatters: "Community discussion volume can reveal emerging anxieties, but it must stay separate from verified news and official policy.",
    whoIsAffected: ["Students", "Families", "Education agents"],
    sourceName: "Community Pulse",
    sourceUrl: "https://example.com/community-pulse-policy",
    category: "Community Pulse",
    subcategory: "Trending Discussions",
    region: "Africa",
    country: "Nigeria",
    publishedAt: "2026-05-18T04:55:00.000Z",
    originalUrl: "https://example.com/community-pulse",
    readTime: "2 min",
    trustScore: 62,
    tags: ["Nigeria", "Community Pulse", "Students", "Visa discussion"],
    contentType: "article",
    providerType: "community_trend",
    sensitivityLevel: "immigration",
    disclaimerRequired: true,
    fetchedAt: now
  },
  {
    id: "singapore-business-costs-local-watch",
    title: "Singapore firms prepare for higher operating-cost pressure",
    summary: "Local publishers are tracking rent, labour, and compliance cost concerns as small firms adjust pricing and staffing plans.",
    keyPoints: ["Business costs remain a local headline theme.", "SMEs are watching rent and wage pressure.", "Regional trade exposure is part of the story."],
    whyItMatters: "Local business coverage helps professionals understand how macro shifts are landing in specific markets.",
    whoIsAffected: ["SMEs", "Workers", "Investors"],
    sourceName: "AsiaOne",
    sourceUrl: "https://www.asiaone.com/",
    category: "Local",
    subcategory: "Business/economy",
    region: "Asia Pacific",
    country: "Singapore",
    publishedAt: "2026-05-18T04:40:00.000Z",
    imageUrl: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=900&q=80",
    originalUrl: "https://www.asiaone.com/",
    readTime: "3 min",
    trustScore: 80,
    tags: ["Singapore", "Business", "Local news"],
    contentType: "article",
    providerType: "rss",
    fetchedAt: now
  },
  {
    id: "gulf-policy-business-brief",
    title: "Gulf policy watchers track business visa and investment-rule updates",
    summary: "Regional coverage is focusing on business mobility, investor incentives, and official rule changes across Gulf markets.",
    keyPoints: ["Policy and visa signals remain intertwined.", "Business mobility is a regional competitiveness theme.", "Official sources should confirm country-specific rules."],
    whyItMatters: "Professionals working across the Gulf need a combined local, policy, and immigration view.",
    whoIsAffected: ["Founders", "Investors", "Skilled workers"],
    sourceName: "Gulf Today",
    sourceUrl: "https://www.gulftoday.ae/",
    category: "Politics & Policy",
    subcategory: "Policy Watch",
    region: "Middle East",
    country: "Middle East",
    publishedAt: "2026-05-18T04:05:00.000Z",
    imageUrl: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=900&q=80",
    originalUrl: "https://www.gulftoday.ae/",
    readTime: "4 min",
    trustScore: 78,
    tags: ["Middle East", "Business", "Policy"],
    contentType: "policy_update",
    providerType: "directory_only",
    sensitivityLevel: "legal",
    disclaimerRequired: true,
    fetchedAt: now
  },
  {
    id: "uk-post-study-stem-extension",
    title: "UK extends post-study work route for STEM graduates",
    summary: "A proposed route extension would give eligible STEM graduates more time to transition into skilled employment while sponsor demand remains high.",
    keyPoints: ["STEM graduates are the initial focus.", "Sponsor licence demand may rise among employers.", "Final eligibility should be checked on GOV.UK."],
    whyItMatters: "Students, universities, and employers need early visibility to plan applications, hiring, and compliance requirements.",
    whoIsAffected: ["International students", "Universities", "UK sponsors"],
    sourceName: "Campus Compass",
    sourceUrl: "https://www.gov.uk/student-visa",
    category: "Students",
    subcategory: "Graduate/post-study route",
    region: "Europe",
    country: "UK",
    publishedAt: "2026-05-18T04:20:00.000Z",
    imageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=900&q=80",
    originalUrl: "https://www.gov.uk/student-visa",
    readTime: "4 min",
    trustScore: 95,
    tags: ["UK", "Post-study work", "STEM"],
    contentType: "visa_update",
    providerType: "official_update_page",
    sensitivityLevel: "immigration",
    disclaimerRequired: true,
    fetchedAt: now
  },
  {
    id: "ai-agents-enterprise-observability",
    title: "Enterprise AI teams shift focus to agent observability",
    summary: "New AI operations tools are prioritising traces, cost controls, evals, and incident review workflows as agent systems move into production.",
    keyPoints: ["Observability is becoming a core AI platform requirement.", "Cost and reliability controls are high-priority buying signals.", "Developer teams are standardising eval workflows."],
    whyItMatters: "Production AI teams need governance and debugging layers before agent systems become dependable business infrastructure.",
    whoIsAffected: ["AI teams", "Developers", "CIOs", "Startup founders"],
    sourceName: "Tech Signal",
    sourceUrl: "https://example.com/tech-signal",
    category: "AI & Technology",
    subcategory: "AI operations",
    region: "Global",
    publishedAt: "2026-05-18T03:45:00.000Z",
    imageUrl: "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=900&q=80",
    originalUrl: "https://example.com/ai-agent-observability",
    readTime: "4 min",
    trustScore: 86,
    tags: ["AI", "Agents", "Observability"],
    contentType: "article",
    providerType: "api",
    fetchedAt: now
  },
  {
    id: "typescript-build-tools-speed-race",
    title: "TypeScript build tools compete on speed and reliability",
    summary: "Developer tooling projects are converging around faster bundling, stricter type workflows, and improved monorepo ergonomics.",
    keyPoints: ["Build performance remains a major adoption driver.", "Monorepo support is shaping tool choices.", "TypeScript-first libraries are gaining attention."],
    whyItMatters: "Tooling shifts can reduce developer wait time and influence architecture choices for new web products.",
    whoIsAffected: ["Frontend teams", "Open-source maintainers", "Engineering managers"],
    sourceName: "DevSignal",
    sourceUrl: "https://example.com/devsignal",
    category: "Developer Trends",
    subcategory: "TypeScript",
    region: "Global",
    publishedAt: "2026-05-18T02:20:00.000Z",
    imageUrl: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=900&q=80",
    originalUrl: "https://example.com/typescript-build-tools",
    readTime: "3 min",
    trustScore: 84,
    tags: ["TypeScript", "Build tools", "Web development"],
    contentType: "article",
    providerType: "api",
    fetchedAt: now
  },
  {
    id: "australia-sponsorship-compliance",
    title: "Australia tightens sponsorship obligations for employers",
    summary: "Updated sponsor compliance guidance puts more emphasis on record keeping, salary evidence, and timely reporting of worker changes.",
    keyPoints: ["Employer record keeping is a central theme.", "Compliance teams should review sponsored worker changes.", "Applicants should check whether their sponsor remains eligible."],
    whyItMatters: "Small errors can delay hiring and create compliance exposure for employers using sponsored routes.",
    whoIsAffected: ["Australian sponsors", "Skilled workers", "HR teams"],
    sourceName: "WorkPath Updates",
    sourceUrl: "https://immi.homeaffairs.gov.au/",
    category: "Work & Sponsorship",
    subcategory: "Sponsor licence",
    country: "Australia",
    publishedAt: "2026-05-18T03:30:00.000Z",
    imageUrl: "https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=900&q=80",
    originalUrl: "https://immi.homeaffairs.gov.au/",
    readTime: "5 min",
    trustScore: 94,
    tags: ["Australia", "Sponsorship", "Employer compliance"],
    contentType: "official_notice",
    providerType: "official_update_page",
    sensitivityLevel: "immigration",
    disclaimerRequired: true,
    fetchedAt: now
  },
  {
    id: "us-senate-export-control-bill",
    title: "US Senate advances tech competition and export control bill",
    summary: "A bipartisan committee vote advanced legislation that would expand reporting duties for sensitive technology transfers and strategic sectors.",
    keyPoints: ["The bill targets sensitive technology supply chains.", "Compliance requirements may expand for exporters.", "Business groups are asking for clearer definitions."],
    whyItMatters: "Policy watchers and founders need to understand whether new compliance duties affect cross-border sales, chips, AI, and cybersecurity tools.",
    whoIsAffected: ["Exporters", "AI startups", "Hardware companies", "Policy teams"],
    sourceName: "Policy Pulse",
    sourceUrl: "https://example.com/policy-pulse",
    category: "Politics & Policy",
    subcategory: "Regulation",
    country: "United States",
    publishedAt: "2026-05-18T02:55:00.000Z",
    imageUrl: "https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?auto=format&fit=crop&w=900&q=80",
    originalUrl: "https://example.com/export-control-bill",
    readTime: "6 min",
    trustScore: 84,
    tags: ["US policy", "Export controls", "Technology"],
    contentType: "policy_update",
    providerType: "api",
    sensitivityLevel: "legal",
    disclaimerRequired: true,
    fetchedAt: now
  },
  {
    id: "open-source-llm-record-contributions",
    title: "Open-source LLM projects see record contributions",
    summary: "Repository activity around evaluation tools, inference optimization, and agent frameworks accelerated sharply over the past week.",
    keyPoints: ["TypeScript agent frameworks are gaining stars.", "Python inference tools remain the largest cluster.", "Evaluation and observability repos are seeing repeat contributor growth."],
    whyItMatters: "GitHub activity can reveal where developer attention is moving before commercial product categories settle.",
    whoIsAffected: ["Developers", "AI founders", "Engineering managers"],
    sourceName: "DevSignal",
    sourceUrl: "https://docs.github.com/en/rest/search/search",
    category: "GitHub Trends",
    subcategory: "AI tools",
    region: "Global",
    publishedAt: "2026-05-18T01:40:00.000Z",
    imageUrl: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=900&q=80",
    originalUrl: "https://github.com/search?q=topic%3Aai&type=repositories",
    readTime: "3 min",
    trustScore: 90,
    tags: ["GitHub", "AI tools", "Open source"],
    contentType: "repo",
    providerType: "api",
    fetchedAt: now
  },
  {
    id: "vpn-critical-vulnerability",
    title: "Critical vulnerability patched in popular VPN software",
    summary: "Security teams are advised to prioritise patching after researchers disclosed an authentication bypass affecting exposed gateway deployments.",
    keyPoints: ["The flaw affects internet-facing gateways.", "Patch availability has been confirmed by the vendor.", "Indicators of compromise should be reviewed after updating."],
    whyItMatters: "Remote access infrastructure is a frequent target, and delayed patching can increase breach risk.",
    whoIsAffected: ["Security teams", "IT admins", "Managed service providers"],
    sourceName: "ThreatLens",
    sourceUrl: "https://example.com/threatlens",
    category: "Cybersecurity",
    subcategory: "Vulnerabilities",
    publishedAt: "2026-05-18T00:35:00.000Z",
    imageUrl: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=900&q=80",
    originalUrl: "https://example.com/vpn-critical-vulnerability",
    readTime: "4 min",
    trustScore: 88,
    tags: ["Security", "VPN", "Patch"],
    contentType: "article",
    providerType: "rss",
    fetchedAt: now
  },
  {
    id: "eu-ai-act-business-explainer",
    title: "EU AI Act: what companies need to know",
    summary: "A concise video explainer breaks down risk categories, documentation requirements, and early governance steps for product teams.",
    keyPoints: ["Risk categories shape obligations.", "Documentation and human oversight are recurring requirements.", "Teams should inventory AI systems early."],
    whyItMatters: "AI governance work takes time, and companies can reduce disruption by mapping obligations before enforcement deadlines.",
    whoIsAffected: ["Product teams", "Founders", "Compliance leads"],
    sourceName: "Visual Briefs",
    sourceUrl: "https://www.youtube.com/",
    category: "Video Briefs",
    subcategory: "AI Policy",
    region: "Europe",
    publishedAt: "2026-05-17T22:10:00.000Z",
    imageUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=900&q=80",
    originalUrl: "https://www.youtube.com/",
    readTime: "3:45",
    trustScore: 82,
    tags: ["Video", "EU AI Act", "Business"],
    contentType: "video",
    providerType: "api",
    sensitivityLevel: "legal",
    disclaimerRequired: true,
    fetchedAt: now
  },
  {
    id: "clean-energy-investment-hubs",
    title: "Clean energy investment hubs gain new funding",
    summary: "A policy-linked investment programme is directing capital toward grid upgrades, storage manufacturing, and local workforce training.",
    keyPoints: ["Grid upgrades are receiving dedicated support.", "Storage manufacturing remains a priority.", "Local skills programmes are attached to the funding."],
    whyItMatters: "Regional funding can reshape jobs, supplier demand, and business opportunities in clean energy markets.",
    whoIsAffected: ["Energy firms", "Local governments", "Workers"],
    sourceName: "Green Horizon",
    sourceUrl: "https://example.com/green-horizon",
    category: "Startups & Business",
    subcategory: "Energy",
    publishedAt: "2026-05-17T20:00:00.000Z",
    imageUrl: "https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=900&q=80",
    originalUrl: "https://example.com/clean-energy-hubs",
    readTime: "4 min",
    trustScore: 81,
    tags: ["Clean energy", "Investment", "Jobs"],
    contentType: "article",
    providerType: "rss",
    fetchedAt: now
  },
  {
    id: "exoplanet-habitable-zone",
    title: "New exoplanet discovery beyond the habitable zone",
    summary: "Researchers reported a cold super-Earth candidate whose orbit may help refine models for planetary formation in distant systems.",
    keyPoints: ["The planet candidate sits beyond the classical habitable zone.", "Follow-up observations are needed.", "The discovery improves formation models."],
    whyItMatters: "Planetary catalogues help researchers understand how common Earth-like and super-Earth systems may be.",
    whoIsAffected: ["Researchers", "Science educators", "Space agencies"],
    sourceName: "Science Scope",
    sourceUrl: "https://openalex.org/",
    category: "Research & Science",
    subcategory: "Space",
    publishedAt: "2026-05-17T18:30:00.000Z",
    imageUrl: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=900&q=80",
    originalUrl: "https://openalex.org/",
    readTime: "3:28",
    trustScore: 86,
    tags: ["Research", "Space", "Exoplanet"],
    contentType: "research",
    providerType: "api",
    fetchedAt: now
  },
  {
    id: "public-health-birth-control-policy",
    title: "Public health agencies review birth control access guidance",
    summary: "Health policy groups are tracking new access guidance and pharmacy-level changes, with official advice differing by jurisdiction.",
    keyPoints: ["Access rules vary by country and state.", "Official health agencies remain the preferred source.", "No personalised medical advice is provided in this brief."],
    whyItMatters: "Policy and access changes can affect families, clinicians, pharmacies, employers, and public health programmes.",
    whoIsAffected: ["Patients", "Clinicians", "Public health teams", "Families"],
    sourceName: "Health Policy Watch",
    sourceUrl: "https://example.com/health-policy",
    category: "Health & Lifestyle",
    subcategory: "Public health",
    publishedAt: "2026-05-17T16:30:00.000Z",
    imageUrl: "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=900&q=80",
    originalUrl: "https://example.com/birth-control-access",
    readTime: "4 min",
    trustScore: 83,
    tags: ["Health", "Family planning", "Policy"],
    contentType: "article",
    providerType: "rss",
    sensitivityLevel: "health",
    disclaimerRequired: true,
    fetchedAt: now
  },
  {
    id: "premium-laptop-review-signal",
    title: "Premium laptop review signals shift toward local AI performance",
    summary: "Reviewers are increasingly scoring laptops on neural performance, battery consistency, repairability, and creator workflow stability.",
    keyPoints: ["Local AI acceleration is becoming a review factor.", "Battery life under sustained workloads matters more.", "Restricted review sources remain directory-only unless licensed."],
    whyItMatters: "Product buyers and creators need a quick way to compare review consensus without losing source attribution.",
    whoIsAffected: ["Consumers", "Creators", "IT buyers"],
    sourceName: "Review Signal",
    sourceUrl: "https://example.com/review-signal",
    category: "Product Reviews",
    subcategory: "Laptops",
    publishedAt: "2026-05-17T14:20:00.000Z",
    imageUrl: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80",
    originalUrl: "https://example.com/premium-laptop-review",
    readTime: "4 min",
    trustScore: 78,
    tags: ["Reviews", "Laptops", "AI PCs"],
    contentType: "review",
    providerType: "directory_only",
    fetchedAt: now
  }
];

export const heroBrief = briefs[0];

export function getBriefById(id: string) {
  return briefs.find((brief) => brief.id === id);
}

export function getBriefsByCategory(category: string) {
  return briefs.filter((brief) => brief.category === category);
}

export function getRelatedBriefs(current: SignalBrief, limit = 3) {
  return briefs
    .filter((brief) => brief.id !== current.id)
    .filter((brief) => brief.category === current.category || brief.tags.some((tag) => current.tags.includes(tag)))
    .slice(0, limit);
}

export const trendRows = [
  { label: "AI Policy", value: "+72%", tone: "text-emerald-500", points: "M 0 20 L 10 18 L 18 10 L 28 14 L 38 5 L 48 9 L 58 3 L 68 5 L 78 0" },
  { label: "Immigration", value: "+28%", tone: "text-amber-500", points: "M 0 14 L 10 11 L 18 17 L 28 9 L 38 12 L 48 8 L 58 15 L 68 10 L 78 13" },
  { label: "Cybersecurity", value: "+41%", tone: "text-rose-500", points: "M 0 10 L 10 14 L 18 7 L 28 18 L 38 13 L 48 19 L 58 9 L 68 16 L 78 12" },
  { label: "Student Visas", value: "+19%", tone: "text-emerald-500", points: "M 0 17 L 10 14 L 18 16 L 28 10 L 38 11 L 48 6 L 58 8 L 68 5 L 78 7" }
];

export const githubFilters = [
  "AI tools",
  "cybersecurity tools",
  "JavaScript",
  "TypeScript",
  "Python",
  "data science",
  "web development",
  "open-source tools",
  "recently updated",
  "created recently",
  "stars and activity"
];
