import type { SourceRegistryEntry, TrustTier } from "@/lib/types";

export const sourceTierLabels: Record<TrustTier, string> = {
  official: "Official",
  verified: "Verified Publisher",
  business: "Business Source",
  community: "Community Trend",
  lifestyle: "Lifestyle Source",
  directory: "Directory Source"
};

export const countries = [
  "Global",
  "Nigeria",
  "UK",
  "USA",
  "Canada",
  "Australia",
  "Singapore",
  "Middle East",
  "India",
  "China",
  "Malaysia",
  "Germany",
  "Africa",
  "Europe"
];

export const sourceRegistry: SourceRegistryEntry[] = [
  {
    id: "global-news-api",
    country: "Global",
    region: "Global",
    name: "Global News API",
    sourceType: "news_publisher",
    sourceCategory: "Global and local headlines",
    mode: "api",
    language: "Multi-language",
    contentCategories: ["World", "Local", "Business", "Technology", "Entertainment"],
    homepage: "https://gnews.io/",
    apiUrl: "https://gnews.io/api/v4",
    trustTier: "verified",
    notes: "API-backed headline provider. Publisher attribution is shown on individual stories, not exposed as a sourcing playbook."
  },
  {
    id: "guardian-open-platform",
    country: "UK",
    region: "Europe",
    name: "The Guardian Open Platform",
    sourceType: "news_publisher",
    sourceCategory: "World, politics, technology, culture",
    mode: "api",
    language: "English",
    contentCategories: ["World", "Politics", "Technology", "Culture"],
    homepage: "https://open-platform.theguardian.com/",
    apiUrl: "https://content.guardianapis.com/search",
    trustTier: "verified",
    notes: "API source for permitted metadata, trail text, thumbnails, and original URLs."
  },
  {
    id: "bbc-rss",
    country: "UK",
    region: "Europe",
    name: "BBC RSS",
    sourceType: "news_publisher",
    sourceCategory: "UK, world, business, politics",
    mode: "rss",
    language: "English",
    contentCategories: ["UK", "World", "Politics", "Business"],
    homepage: "https://www.bbc.com/news",
    feedUrl: "https://feeds.bbci.co.uk/news/rss.xml",
    trustTier: "verified",
    notes: "RSS metadata source. Full articles remain with the publisher."
  },
  {
    id: "al-jazeera-rss",
    country: "Global",
    region: "Middle East",
    name: "Al Jazeera RSS",
    sourceType: "news_publisher",
    sourceCategory: "International and Middle East news",
    mode: "rss",
    language: "English",
    contentCategories: ["World", "Middle East", "Politics", "Video"],
    homepage: "https://www.aljazeera.com/",
    feedUrl: "https://www.aljazeera.com/xml/rss/all.xml",
    trustTier: "verified",
    notes: "Permitted feed metadata and original source links only."
  },
  {
    id: "country-local-api",
    country: "Global",
    region: "Global",
    name: "Country Local Headlines",
    sourceType: "news_publisher",
    sourceCategory: "Country and city-level local feeds",
    mode: "api",
    language: "Multi-language",
    contentCategories: ["Local", "Business", "Politics", "Lifestyle", "Technology"],
    homepage: "https://gnews.io/",
    apiUrl: "https://gnews.io/api/v4/top-headlines",
    trustTier: "verified",
    notes: "Country filters power local pages. Story cards show publisher attribution after normalization."
  },
  {
    id: "community-pulse-provider",
    country: "Global",
    region: "Global",
    name: "Community Pulse Provider",
    sourceType: "community_forum",
    sourceCategory: "Aggregated public discussion signals",
    mode: "community_trend",
    language: "Multi-language",
    contentCategories: ["Community Pulse", "Trending Discussions"],
    homepage: "https://example.com/community-pulse-policy",
    trustTier: "community",
    notes: "Community signals are never mixed with verified news. They appear as pulse/trend context only."
  },
  {
    id: "youtube-data-api",
    country: "Global",
    region: "Global",
    name: "YouTube Data API",
    sourceType: "video_channel",
    sourceCategory: "Video explainers",
    mode: "api",
    language: "Multi-language",
    contentCategories: ["Video", "Explainers", "Technology", "Policy"],
    homepage: "https://developers.google.com/youtube/v3",
    apiUrl: "https://www.googleapis.com/youtube/v3",
    trustTier: "verified",
    notes: "Selected channel and playlist metadata for internal video brief pages."
  },
  {
    id: "github-search-api",
    country: "Global",
    region: "Global",
    name: "GitHub Search API",
    sourceType: "technology",
    sourceCategory: "Developer and repository trends",
    mode: "api",
    language: "English",
    contentCategories: ["Developers", "GitHub", "AI", "Cybersecurity"],
    homepage: "https://docs.github.com/en/rest/search/search",
    apiUrl: "https://api.github.com/search/repositories",
    trustTier: "verified",
    notes: "Repository trend signals based on search queries because GitHub has no official Trending API endpoint."
  },
  {
    id: "govuk-home-office",
    country: "UK",
    region: "Europe",
    name: "GOV.UK Home Office",
    sourceType: "official_government",
    sourceCategory: "Immigration, visas, right-to-work, sponsorship",
    mode: "official_update_page",
    language: "English",
    contentCategories: ["Visa", "Immigration", "Policy", "Official Updates"],
    homepage: "https://www.gov.uk/government/organisations/home-office",
    trustTier: "official",
    notes: "Official immigration and policy source."
  },
  {
    id: "uscis",
    country: "USA",
    region: "North America",
    name: "USCIS",
    sourceType: "official_government",
    sourceCategory: "US immigration notices and alerts",
    mode: "official_update_page",
    language: "English",
    contentCategories: ["Visa", "Immigration", "Official Updates", "Policy"],
    homepage: "https://www.uscis.gov/newsroom",
    trustTier: "official",
    notes: "Official US immigration update source."
  },
  {
    id: "ircc",
    country: "Canada",
    region: "North America",
    name: "IRCC Canada",
    sourceType: "official_government",
    sourceCategory: "Canada immigration notices",
    mode: "official_update_page",
    language: "English/French",
    contentCategories: ["Visa", "Immigration", "Students", "Official Updates"],
    homepage: "https://www.canada.ca/en/immigration-refugees-citizenship/news.html",
    trustTier: "official",
    notes: "Official Canada immigration and citizenship update source."
  },
  {
    id: "australia-home-affairs",
    country: "Australia",
    region: "Oceania",
    name: "Australia Department of Home Affairs",
    sourceType: "official_government",
    sourceCategory: "Australia visas and immigration",
    mode: "official_update_page",
    language: "English",
    contentCategories: ["Visa", "Immigration", "Work", "Official Updates"],
    homepage: "https://immi.homeaffairs.gov.au/news-media/archive",
    trustTier: "official",
    notes: "Official Australia immigration and border policy updates."
  },
  {
    id: "germany-foreign-office",
    country: "Germany",
    region: "Europe",
    name: "Germany Federal Foreign Office",
    sourceType: "official_government",
    sourceCategory: "Germany visa information",
    mode: "official_update_page",
    language: "German/English",
    contentCategories: ["Visa", "Immigration", "Official Updates"],
    homepage: "https://www.auswaertiges-amt.de/en/visa-service",
    trustTier: "official",
    notes: "Official Germany visa and consular information."
  },
  {
    id: "india-boi",
    country: "India",
    region: "Asia",
    name: "India Bureau of Immigration",
    sourceType: "official_government",
    sourceCategory: "India immigration",
    mode: "official_update_page",
    language: "English",
    contentCategories: ["Visa", "Immigration", "Official Updates"],
    homepage: "https://boi.gov.in/",
    trustTier: "official",
    notes: "Official India immigration information entry point."
  },
  {
    id: "china-visa-service",
    country: "China",
    region: "Asia",
    name: "China Visa Application Service",
    sourceType: "official_government",
    sourceCategory: "China visa service",
    mode: "official_update_page",
    language: "Chinese/English",
    contentCategories: ["Visa", "Immigration", "Official Updates"],
    homepage: "https://www.visaforchina.cn/",
    trustTier: "official",
    notes: "Official visa service entry point for China-related visa updates."
  },
  {
    id: "malaysia-immigration",
    country: "Malaysia",
    region: "Asia",
    name: "Immigration Department of Malaysia",
    sourceType: "official_government",
    sourceCategory: "Malaysia immigration",
    mode: "official_update_page",
    language: "Malay/English",
    contentCategories: ["Visa", "Immigration", "Official Updates"],
    homepage: "https://www.imi.gov.my/",
    trustTier: "official",
    notes: "Official Malaysia immigration information and notices."
  }
];

export function getSourcesByCountry(country: string) {
  if (country === "Global") return sourceRegistry;
  return sourceRegistry.filter((source) => source.country === country || source.region === country);
}
