import type { SourceRegistryEntry, TrustTier } from "@/lib/types";

export const sourceTierLabels: Record<TrustTier, string> = {
  official: "Official",
  verified: "Verified Publisher",
  business: "Business Source",
  community: "Community Trend",
  lifestyle: "Lifestyle Source",
  directory: "Directory Source"
};

export const countries = [
  "Global",
  "Nigeria",
  "UK",
  "USA",
  "Canada",
  "Australia",
  "Singapore",
  "Middle East",
  "India",
  "China",
  "Malaysia",
  "Germany",
  "Africa",
  "Europe"
];

export const sourceRegistry: SourceRegistryEntry[] = [
  {
    id: "newsdata",
    providerId: "newsdata",
    requiredEnvVar: "NEWSDATA_API_KEY",
    country: "Global",
    region: "Global",
    name: "NewsData.io",
    sourceType: "news_publisher",
    sourceCategory: "General, world, business, local, and technology search",
    mode: "api",
    language: "Multi-language",
    contentCategories: ["World", "Local", "Business", "Technology"],
    homepage: "https://newsdata.io/",
    apiUrl: "https://newsdata.io/api/1/latest",
    trustTier: "verified",
    notes: "Free-tier general news API for category, country, language, and keyword search."
  },
  {
    id: "gnews",
    providerId: "gnews",
    requiredEnvVar: "GNEWS_API_KEY",
    country: "Global",
    region: "Global",
    name: "GNews",
    sourceType: "news_publisher",
    sourceCategory: "Headline and search fallback",
    mode: "api",
    language: "Multi-language",
    contentCategories: ["World", "Local", "Business", "Technology"],
    homepage: "https://gnews.io/",
    apiUrl: "https://gnews.io/api/v4",
    trustTier: "verified",
    notes: "General headline and keyword search provider used as one of the live fallback sources."
  },
  {
    id: "newsapi",
    providerId: "newsapi",
    requiredEnvVar: "NEWSAPI_API_KEY",
    country: "Global",
    region: "Global",
    name: "NewsAPI.org",
    sourceType: "news_publisher",
    sourceCategory: "Headline and search fallback",
    mode: "api",
    language: "Multi-language",
    contentCategories: ["World", "Business", "Technology", "Politics"],
    homepage: "https://newsapi.org/",
    apiUrl: "https://newsapi.org/v2/everything",
    trustTier: "verified",
    notes: "Free-tier general news provider used for live keyword search where available."
  },
  {
    id: "eventregistry",
    providerId: "eventregistry",
    requiredEnvVar: "EVENTREGISTRY_API_KEY",
    country: "Global",
    region: "Global",
    name: "Event Registry",
    sourceType: "news_publisher",
    sourceCategory: "Topic clustering and event search",
    mode: "api",
    language: "Multi-language",
    contentCategories: ["World", "Policy", "Business", "Technology"],
    homepage: "https://newsapi.ai/",
    apiUrl: "https://eventregistry.org/api/v1/article/getArticles",
    trustTier: "verified",
    notes: "Optional enrichment source for entity and topic discovery when a trial key is available."
  },
  {
    id: "guardian-open-platform",
    providerId: "guardian",
    requiredEnvVar: "GUARDIAN_API_KEY",
    country: "UK",
    region: "Europe",
    name: "The Guardian Open Platform",
    sourceType: "news_publisher",
    sourceCategory: "World, politics, technology, students, and business",
    mode: "api",
    language: "English",
    contentCategories: ["World", "Politics", "Students", "Technology", "Business"],
    homepage: "https://open-platform.theguardian.com/",
    apiUrl: "https://content.guardianapis.com/search",
    trustTier: "verified",
    notes: "Trusted editorial metadata source for UK, policy, education, and world coverage."
  },
  {
    id: "bbc-rss",
    providerId: "rssSources",
    country: "UK",
    region: "Europe",
    name: "BBC RSS",
    sourceType: "news_publisher",
    sourceCategory: "World, UK, business, and technology RSS",
    mode: "rss",
    language: "English",
    contentCategories: ["World", "Local", "Business", "Technology"],
    homepage: "https://www.bbc.com/news",
    feedUrl: "https://feeds.bbci.co.uk/news/rss.xml",
    trustTier: "verified",
    notes: "Public RSS source used for live metadata and original publisher links."
  },
  {
    id: "al-jazeera-rss",
    providerId: "rssSources",
    country: "Global",
    region: "Middle East",
    name: "Al Jazeera RSS",
    sourceType: "news_publisher",
    sourceCategory: "International and Middle East RSS",
    mode: "rss",
    language: "English",
    contentCategories: ["World", "Politics", "Middle East"],
    homepage: "https://www.aljazeera.com/",
    feedUrl: "https://www.aljazeera.com/xml/rss/all.xml",
    trustTier: "verified",
    notes: "Public RSS feed used for world and policy discovery."
  },
  {
    id: "github-search-api",
    providerId: "githubSearch",
    requiredEnvVar: "GITHUB_TOKEN",
    country: "Global",
    region: "Global",
    name: "GitHub REST API",
    sourceType: "technology",
    sourceCategory: "Repository search and metadata",
    mode: "api",
    language: "English",
    contentCategories: ["GitHub", "AI", "Cybersecurity", "Developers"],
    homepage: "https://docs.github.com/en/rest/search/search",
    apiUrl: "https://api.github.com/search/repositories",
    trustTier: "verified",
    notes: "Used for repository search, stars, language, and README enrichment. Public access works with lower rate limits."
  },
  {
    id: "github-trending",
    providerId: "githubTrending",
    requiredEnvVar: "GITHUB_TOKEN",
    country: "Global",
    region: "Global",
    name: "GitHub Trending",
    sourceType: "technology",
    sourceCategory: "Trending repository discovery",
    mode: "api",
    language: "English",
    contentCategories: ["GitHub", "Open source", "Developer tools"],
    homepage: "https://github.com/trending",
    trustTier: "verified",
    notes: "Public trending repository discovery enriched with GitHub REST metadata."
  },
  {
    id: "govuk-home-office",
    providerId: "officialFeeds",
    country: "UK",
    region: "Europe",
    name: "GOV.UK Home Office",
    sourceType: "official_government",
    sourceCategory: "Immigration, visas, right-to-work, sponsorship",
    mode: "official_update_page",
    language: "English",
    contentCategories: ["Visa", "Immigration", "Policy", "Official Updates"],
    homepage: "https://www.gov.uk/government/organisations/home-office",
    trustTier: "official",
    notes: "Official Home Office policy and immigration update source."
  },
  {
    id: "uscis",
    providerId: "officialFeeds",
    country: "USA",
    region: "North America",
    name: "USCIS",
    sourceType: "official_government",
    sourceCategory: "US immigration notices and alerts",
    mode: "official_update_page",
    language: "English",
    contentCategories: ["Visa", "Immigration", "Official Updates", "Policy"],
    homepage: "https://www.uscis.gov/newsroom",
    trustTier: "official",
    notes: "Official US immigration source listed for live official-update monitoring."
  },
  {
    id: "ircc",
    providerId: "officialFeeds",
    country: "Canada",
    region: "North America",
    name: "IRCC Canada",
    sourceType: "official_government",
    sourceCategory: "Canada immigration notices",
    mode: "official_update_page",
    language: "English/French",
    contentCategories: ["Visa", "Immigration", "Students", "Official Updates"],
    homepage: "https://www.canada.ca/en/immigration-refugees-citizenship/news.html",
    trustTier: "official",
    notes: "Official Canada immigration and citizenship update source."
  },
  {
    id: "australia-home-affairs",
    providerId: "officialFeeds",
    country: "Australia",
    region: "Oceania",
    name: "Australia Department of Home Affairs",
    sourceType: "official_government",
    sourceCategory: "Australia visas and immigration",
    mode: "official_update_page",
    language: "English",
    contentCategories: ["Visa", "Immigration", "Work", "Official Updates"],
    homepage: "https://immi.homeaffairs.gov.au/news-media/archive",
    trustTier: "official",
    notes: "Official Australian immigration and border policy update source."
  },
  {
    id: "germany-foreign-office",
    providerId: "officialFeeds",
    country: "Germany",
    region: "Europe",
    name: "Germany Federal Foreign Office",
    sourceType: "official_government",
    sourceCategory: "Germany visa information",
    mode: "official_update_page",
    language: "German/English",
    contentCategories: ["Visa", "Immigration", "Official Updates"],
    homepage: "https://www.auswaertiges-amt.de/en/visa-service",
    trustTier: "official",
    notes: "Official Germany visa and consular information source."
  },
  {
    id: "india-boi",
    providerId: "officialFeeds",
    country: "India",
    region: "Asia",
    name: "India Bureau of Immigration",
    sourceType: "official_government",
    sourceCategory: "India immigration",
    mode: "official_update_page",
    language: "English",
    contentCategories: ["Visa", "Immigration", "Official Updates"],
    homepage: "https://boi.gov.in/",
    trustTier: "official",
    notes: "Official India immigration information entry point."
  },
  {
    id: "china-visa-service",
    providerId: "officialFeeds",
    country: "China",
    region: "Asia",
    name: "China Visa Application Service",
    sourceType: "official_government",
    sourceCategory: "China visa service",
    mode: "official_update_page",
    language: "Chinese/English",
    contentCategories: ["Visa", "Immigration", "Official Updates"],
    homepage: "https://www.visaforchina.cn/",
    trustTier: "official",
    notes: "Official China visa service entry point."
  },
  {
    id: "malaysia-immigration",
    providerId: "officialFeeds",
    country: "Malaysia",
    region: "Asia",
    name: "Immigration Department of Malaysia",
    sourceType: "official_government",
    sourceCategory: "Malaysia immigration",
    mode: "official_update_page",
    language: "Malay/English",
    contentCategories: ["Visa", "Immigration", "Official Updates"],
    homepage: "https://www.imi.gov.my/",
    trustTier: "official",
    notes: "Official Malaysia immigration information and notices."
  },
  {
    id: "cisa",
    providerId: "cyberFeeds",
    country: "USA",
    region: "Global",
    name: "CISA Cybersecurity Advisories",
    sourceType: "cybersecurity",
    sourceCategory: "Official vulnerability and incident advisories",
    mode: "official_update_page",
    language: "English",
    contentCategories: ["Cybersecurity", "Official Updates", "Advisories"],
    homepage: "https://www.cisa.gov/news-events/cybersecurity-advisories",
    feedUrl: "https://www.cisa.gov/cybersecurity-advisories/all.xml",
    trustTier: "official",
    notes: "Official cybersecurity advisory feed used for live cyber alerts."
  },
  {
    id: "bleepingcomputer",
    providerId: "cyberFeeds",
    country: "Global",
    region: "Global",
    name: "BleepingComputer",
    sourceType: "cybersecurity",
    sourceCategory: "Security news and incident reporting",
    mode: "rss",
    language: "English",
    contentCategories: ["Cybersecurity", "Advisories", "Security News"],
    homepage: "https://www.bleepingcomputer.com/",
    feedUrl: "https://www.bleepingcomputer.com/feed/",
    trustTier: "verified",
    notes: "Trusted security RSS source used alongside official advisories."
  },
  {
    id: "mediastack",
    providerId: "mediastack",
    requiredEnvVar: "MEDIASTACK_API_KEY",
    country: "Global",
    region: "Global",
    name: "Mediastack",
    sourceType: "news_publisher",
    sourceCategory: "General news backup provider",
    mode: "api",
    language: "Multi-language",
    contentCategories: ["World", "Business", "Technology", "Politics"],
    homepage: "https://mediastack.com/",
    apiUrl: "http://api.mediastack.com/v1/news",
    trustTier: "verified",
    notes: "Backup general news provider when a free key is available."
  },
  {
    id: "community-pulse-provider",
    country: "Global",
    region: "Global",
    name: "Community Trend Sources",
    sourceType: "community_forum",
    sourceCategory: "Public community discussions",
    mode: "community_trend",
    language: "Multi-language",
    contentCategories: ["Community Pulse", "Trending Discussions"],
    homepage: "https://www.reddit.com/",
    trustTier: "community",
    notes: "Reserved for clearly labelled public discussion signals, kept separate from verified news."
  },
  {
    id: "youtube-data-api",
    country: "Global",
    region: "Global",
    name: "YouTube Data API",
    sourceType: "video_channel",
    sourceCategory: "Video explainers",
    mode: "api",
    language: "Multi-language",
    contentCategories: ["Video", "Explainers", "Technology", "Policy"],
    homepage: "https://developers.google.com/youtube/v3",
    apiUrl: "https://www.googleapis.com/youtube/v3",
    trustTier: "verified",
    notes: "Placeholder live-video provider for a later pass."
  }
];

export function getSourcesByCountry(country: string) {
  if (country === "Global") return sourceRegistry;
  return sourceRegistry.filter((source) => source.country === country || source.region === country);
}
